variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
stages:
  - maven
  - deploy

maven:
  image: openjdk:8-jdk-alpine
  stage: maven
  before_script:
    - apk add --no-cache curl tar unzip bash git maven && apk add patch make ca-certificates openssl python --update
    - git config --global user.email "deploy@walrus.network"
    - git config --global user.name "Walrus Deploy"
    # Install CA certs, openssl to https downloads, python for gcloud sdk
    - update-ca-certificates
    # Write our GCP service account private key into a file
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
    # Download and install Google Cloud SDK
    - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
    - tar zxvf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --usage-reporting=false --path-update=true
    - google-cloud-sdk/bin/gcloud --quiet components update
    - google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - google-cloud-sdk/bin/gcloud config set project walrus-network
  script:
    - bash sportpaper build
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
  retry:
    max: 2
    when: stuck_or_timeout_failure

trigger_downstream:
  image: maven:3.6.1-jdk-8-slim
  stage: deploy
  script:
    # Intake
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/14583273/trigger/pipeline
    # Tabbed
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/14583285/trigger/pipeline